SELECT DISTINCT
        MAX_LOTE.CVE_ENTIDAD
        ,EFU.DES_ENTIDAD
        ,MAX(SG.FEC_PERIODO) OVER (PARTITION BY MAX_LOTE.CVE_ENTIDAD) FEC_PERIODO_GLOBAL_ENTIDAD
        ,DES_NOMBRE_ARCHIVO
        ,MAX_LOTE.NUM_LOTE_CARGA
    FROM 
        (
        SELECT CVE_ENTIDAD  
                ,MAX(MAX_FECPER_LOTE_ENTIDAD) MAX_FECPER_LOTE_ENTIDAD
                ,MAX(NUM_LOTE_CARGA) NUM_LOTE_CARGA
                ,MAX(DES_NOMBRE_ARCHIVO) DES_NOMBRE_ARCHIVO
        FROM(
                SELECT  CL.CVE_ENTIDAD  
                        ,CL.FEC_PERIODO
                        ,MAX(CL.FEC_PERIODO) OVER (PARTITION BY CL.CVE_ENTIDAD)  MAX_FECPER_LOTE_ENTIDAD
                        ,CL.NUM_LOTE_CARGA
                        ,CL.DES_NOMBRE_ARCHIVO
                FROM   GPT_CARGA_LOTES CL
                WHERE  CL.FEC_CANCELACION IS NULL
                AND CVE_TIPO_FUENTE = (SELECT GPPG_RC.get_fuente('MOROSIDAD') FROM DUAL)  -- 8 TIPO DE FUENTE  MICROFINANZAS
                AND CL.CVE_ENTIDAD = 50
            )
        WHERE FEC_PERIODO = MAX_FECPER_LOTE_ENTIDAD
        GROUP BY CVE_ENTIDAD            
        ) MAX_LOTE
    INNER JOIN GPT_SALDOS_GENERALES SG
            ON MAX_LOTE.NUM_LOTE_CARGA = SG.NUM_LOTE_CARGA
    INNER JOIN GPC_ENTIDAD_FUENTE EFU
            ON MAX_LOTE.CVE_ENTIDAD = EFU.CVE_ENTIDAD
            AND EFU.CVE_ESTATUS = 1
    ORDER BY CVE_ENTIDAD ASC
    
MERGE INTO GPT_CARGA_LOTES CL
USING (
SELECT NUM_LOTE_CARGA
        ,DES_NOMBRE_ARCHIVO
        ,FEC_PERIODO
        ,(SELECT MAX(FEC_PERIODO) MAX_FEC_PERIODO
            FROM GPT_SALDOS_GENERALES A
                INNER JOIN GPT_MICROFINANZAS C
                        ON A.NUM_PERSONA = C.NUM_PERSONA
                        AND A.NUM_SALDO = C.NUM_SALDO
            WHERE A.NUM_LOTE_CARGA = B.NUM_LOTE_CARGA
                AND C.CVE_ENTIDAD = B.CVE_ENTIDAD
        )  MAX_FEC_PERIODO
FROM GPT_CARGA_LOTES B
WHERE CVE_TIPO_FUENTE = GPPG_RC.get_fuente('MOROSIDAD')
) MAX_FEC_LOTE
ON (CL.NUM_LOTE_CARGA = MAX_FEC_LOTE.NUM_LOTE_CARGA)
WHEN MATCHED THEN
  UPDATE SET CL.FEC_PERIODO = MAX_FEC_LOTE.MAX_FEC_PERIODO;


    
    